app_base_dir: "/usr/local/lib/server"
app_domain: discord.moroz.dev
app_name: discord
app_port: 3000
app_user: app
caddy_release: "2.9.1"
caddyfile_path: "/usr/local/etc/Caddyfile"
deploy_user: deploy
github_username: moroz
